### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by jeevanshah07** [Murzchnvok/ugly-todo#1]
I followed all the instructions listed but when it ran `utd` my console returned an error saying: `zsh: command not found: utd`.

*How to recreate*:
1.Follow installation instructions
2.Run `utd`
3.Get an error

**Comment by Murzchnvok** [comment]
Hmm, maybe it has something to do with the environment variable, add this to your .zshrc file:

```bash
export PATH=$HOME/bin:$PATH
```

**Comment by jeevanshah07** [comment]
Yep that fixed it. Thanks for your help!
